<option value='Hanoi - Đại học Quốc gia Hà Nội (Vietnam National University)'>Hanoi - Đại học Quốc gia Hà Nội (Vietnam National University)</option>
<option value='Hanoi - Đại học Hà Nội + LaTrobe (Hanoi University + LaTrobe)'>Hanoi - Đại học Hà Nội + LaTrobe (Hanoi University + LaTrobe)</option>
<option value='Hanoi - Học viện Ngân hàng (Banking Academy)'>Hanoi - Học viện Ngân hàng (Banking Academy)</option>
<option value='Hanoi - Khoa Quốc Tế - Đại học Quốc Gia Hà Nội (International School - VNU, Hanoi)'>Hanoi - Khoa Quốc Tế - Đại học Quốc Gia Hà Nội (International School - VNU, Hanoi)</option>
<option value='Hanoi - Đại học Khoa Học Xã hội và Nhân văn - ĐHQGHN (University of Social Sciences and Humanities - Hanoi, VNU)'>Hanoi - Đại học Khoa Học Xã hội và Nhân văn - ĐHQGHN (University of Social Sciences and Humanities - Hanoi, VNU)</option>
<option value='Hanoi - Đại học Ngoại Ngữ Hà Nội (University of Languages and International Studies - VNU)'>Hanoi - Đại học Ngoại Ngữ Hà Nội (University of Languages and International Studies - VNU)</option>
<option value='Hanoi - Đại học Bách khoa Hà Nội (Hanoi University of Science and Technology)'>Hanoi - Đại học Bách khoa Hà Nội (Hanoi University of Science and Technology)</option>
<option value='Hanoi - Đại học Thương mại (Vietnam University of Commerce)'>Hanoi - Đại học Thương mại (Vietnam University of Commerce)</option>
<option value='Hanoi - Đại học Khoa học và Công nghệ Hà Nội (University of Science and Technology of Hanoi)'>Hanoi - Đại học Khoa học và Công nghệ Hà Nội (University of Science and Technology of Hanoi)</option>
<option value='Hanoi - Truyền thông đa phương tiện ARENA (ARENA Multimedia)'>Hanoi - Truyền thông đa phương tiện ARENA (ARENA Multimedia)</option>
<option value='Hanoi - Đại học Kinh doanh và Công nghệ (Hanoi University of Business and Technology (HUBT))'>Hanoi - Đại học Kinh doanh và Công nghệ (Hanoi University of Business and Technology (HUBT))</option>
<option value='Hanoi - Đại học Quốc tế RMIT (RMIT University (Hanoi))'>Hanoi - Đại học Quốc tế RMIT (RMIT University (Hanoi))</option>
<option value='Hanoi - Đại học Kiến trúc Hà Nội (Hanoi Architectural University)'>Hanoi - Đại học Kiến trúc Hà Nội (Hanoi Architectural University)</option>
<option value='Hanoi - Đại học Lao động Xã hội HN (University of Labour and Social Affairs)'>Hanoi - Đại học Lao động Xã hội HN (University of Labour and Social Affairs)</option>
<option value='Hanoi - Đại học Kinh tế Kỹ thuật Công nghiệp (University of Economic and Technical Industries)'>Hanoi - Đại học Kinh tế Kỹ thuật Công nghiệp (University of Economic and Technical Industries)</option>
<option value='Hanoi - Đại học Thủy lợi (Water Resources University)'>Hanoi - Đại học Thủy lợi (Water Resources University)</option>
<option value='Hanoi - Đại học Công đoàn (Vietnam Trade Union University)'>Hanoi - Đại học Công đoàn (Vietnam Trade Union University)</option>
<option value='Hanoi - Đại học Nông nghiệp Hà Nội (Hanoi University of Agriculture)'>Hanoi - Đại học Nông nghiệp Hà Nội (Hanoi University of Agriculture)</option>
<option value='Hanoi - Học viện Quân y (Vietnam Military Medical University)'>Hanoi - Học viện Quân y (Vietnam Military Medical University)</option>
<option value='Hanoi - Đại học Đại Nam (Dai Nam University)'>Hanoi - Đại học Đại Nam (Dai Nam University)</option>
<option value='Hanoi - Học viện Thanh Thiếu niên Việt Nam (Vietnam Youth Academy)'>Hanoi - Học viện Thanh Thiếu niên Việt Nam (Vietnam Youth Academy)</option>
<option value='Hanoi - Đại học Công nghiệp Việt Hung (Viet Hung Industrial University)'>Hanoi - Đại học Công nghiệp Việt Hung (Viet Hung Industrial University)</option>
<option value='Hanoi - Đại học Sư phạm Nghệ thuật Trung ương Hà Nội (National University of Art Education)'>Hanoi - Đại học Sư phạm Nghệ thuật Trung ương Hà Nội (National University of Art Education)</option>
<option value='Hanoi - Đại học Tài chính Ngân hàng Hà Nội (Financial and Banking University)'>Hanoi - Đại học Tài chính Ngân hàng Hà Nội (Financial and Banking University)</option>
<option value='Hanoi - Đại học Công nghệ và Quản lý Hữu nghị (Huu Nghi University of Technology and Management)'>Hanoi - Đại học Công nghệ và Quản lý Hữu nghị (Huu Nghi University of Technology and Management)</option>
<option value='Hanoi - Đại học Tài nguyên và Môi trường Hà Nội (Hanoi University of Natural Resources and Environment)'>Hanoi - Đại học Tài nguyên và Môi trường Hà Nội (Hanoi University of Natural Resources and Environment)</option>
<option value='Hanoi - Đại học Y Hà Nội (Hanoi Medical University)'>Hanoi - Đại học Y Hà Nội (Hanoi Medical University)</option>
<option value='Hanoi - Đại học Mỹ thuật Việt Nam (Vietnam University of Fine Arts)'>Hanoi - Đại học Mỹ thuật Việt Nam (Vietnam University of Fine Arts)</option>
<option value='Hanoi - Học viện Nông nghiệp Việt Nam (VNUA) (Vietnam University of Agriculture)'>Hanoi - Học viện Nông nghiệp Việt Nam (VNUA) (Vietnam University of Agriculture)</option>
<option value='Hanoi - University College London (UCL) (University College London (UCL))'>Hanoi - University College London (UCL) (University College London (UCL))</option>
<option value='Hanoi - Trường cao đẳng du lịch Hà Nội (Hanoi tourism college)'>Hanoi - Trường cao đẳng du lịch Hà Nội (Hanoi tourism college)</option>
<option value='Hanoi - Đại học Sư phạm Nghệ thuật Trung ương Hà Nội (National University of Art Education)'>Hanoi - Đại học Sư phạm Nghệ thuật Trung ương Hà Nội (National University of Art Education)</option>
<option value='Hanoi - Đại học Tài chính Ngân hàng Hà Nội (Financial and Banking University)'>Hanoi - Đại học Tài chính Ngân hàng Hà Nội (Financial and Banking University)</option><option value='Hanoi - Đại học Ngoại thương HN (Foreign Trade University)'>Hanoi - Đại học Ngoại thương HN (Foreign Trade University)</option>
<option value='Hanoi - Học viện Ngoại giao (Diplomatic Academy of Vietnam)'>Hanoi - Học viện Ngoại giao (Diplomatic Academy of Vietnam)</option>
<option value='Hanoi - Học viện Báo chí Tuyên truyền (Academy of Journalism and Communication)'>Hanoi - Học viện Báo chí Tuyên truyền (Academy of Journalism and Communication)</option>
<option value='Hanoi - Đại học Sư phạm (National University of Education)'>Hanoi - Đại học Sư phạm (National University of Education)</option>
<option value='Hanoi - Đại học Luật Hà Nội (Hanoi Law University)'>Hanoi - Đại học Luật Hà Nội (Hanoi Law University)</option>
<option value='Hanoi - Đại học FPT HN (FPT University)'>Hanoi - Đại học FPT HN (FPT University)</option>
<option value='Hanoi - Học viện Tài chính (Academy of Finance)'>Hanoi - Học viện Tài chính (Academy of Finance)</option>
<option value='Hanoi - British University Vietnam (British University Vietnam)'>Hanoi - British University Vietnam (British University Vietnam)</option>
<option value='Hanoi - Đại học Mỹ thuật Công nghiệp (Industrial Fine Art University)'>Hanoi - Đại học Mỹ thuật Công nghiệp (Industrial Fine Art University)</option>
<option value='Hanoi - Học viện Công nghệ Bưu chính Viễn thông HN (Posts and Telecommunications Institute of Technology)'>Hanoi - Học viện Công nghệ Bưu chính Viễn thông HN (Posts and Telecommunications Institute of Technology)</option>
<option value='Hanoi - Đại học Công nghệ Giao thông vận tải (University of Transport Technology)'>Hanoi - Đại học Công nghệ Giao thông vận tải (University of Transport Technology)</option>
<option value='Hanoi - Đại học Dược Hà Nội (Hanoi University of Pharmacy)'>Hanoi - Đại học Dược Hà Nội (Hanoi University of Pharmacy)</option>
<option value='Hanoi - Đại học Điện lực (Electric Power University)'>Hanoi - Đại học Điện lực (Electric Power University)</option>
<option value='Hanoi - Đại học Lâm nghiệp (Vietnam Forestry University)'>Hanoi - Đại học Lâm nghiệp (Vietnam Forestry University)</option>
<option value='Hanoi - Học viện An ninh Nhân dân (Peoples Police Academy)'>Hanoi - Học viện An ninh Nhân dân (People's Police Academy)</option>
<option value='Hanoi - Học viện Hành chính Quốc gia (National Academy of Public Administration)'>Hanoi - Học viện Hành chính Quốc gia (National Academy of Public Administration)</option>
<option value='Hanoi - Học viện Y Dược học cổ truyền Việt Nam (Vietnam University of Traditional Medicine)'>Hanoi - Học viện Y Dược học cổ truyền Việt Nam (Vietnam University of Traditional Medicine)</option>
<option value='Hanoi - Đại học Giao thông vận tải HN (University of Communications and Transport)'>Hanoi - Đại học Giao thông vận tải HN (University of Communications and Transport)</option>
<option value='Hanoi - Đại học Nội vụ Hà Nội (University of Home Affairs)'>Hanoi - Đại học Nội vụ Hà Nội (University of Home Affairs)</option>
<option value='Hanoi - Đại học Y tế Công cộng (Hanoi School Of Public Health)'>Hanoi - Đại học Y tế Công cộng (Hanoi School Of Public Health)</option>
<option value='Hanoi - Đại học Nguyễn Trãi'>Hanoi - Đại học Nguyễn Trãi</option>
<option value='Hanoi - Đại học Thành Tây'>Hanoi - Đại học Thành Tây</option>
<option value='Hanoi - Cao đẳng nghề Bách Khoa Hà Nội (Hanoi Vocational College of Technology)'>Hanoi - Cao đẳng nghề Bách Khoa Hà Nội (Hanoi Vocational College of Technology)</option>
<option value='Hanoi - Cao đẳng y tế Hà Đông (Hadong Medical College)'>Hanoi - Cao đẳng y tế Hà Đông (Hadong Medical College)</option>
<option value='Hanoi - Cao đẳng y tế Bạch Mai'>Hanoi - Cao đẳng y tế Bạch Mai</option>
<option value='Hanoi - Đại học Greenwich Hà Nội'>Hanoi - Đại học Greenwich Hà Nội</option>
<option value='Hanoi - Đại học Swinburne Việt Nam'>Hanoi - Đại học Swinburne Việt Nam</option>
<option value='Hanoi - Học viện Tòa án Hà Nội (Vietnam Court Academy)'>Hanoi - Học viện Tòa án Hà Nội (Vietnam Court Academy)</option>
<option value='Hanoi - Trung Cấp Giao Thông Vận Tải'>Hanoi - Trung Cấp Giao Thông Vận Tải</option>
<option value='Hanoi - Đại học Kinh tế Quốc dân (National Economics University)'>Hanoi - Đại học Kinh tế Quốc dân (National Economics University)</option>
<option value='Hanoi - Đại học Thăng Long (Thang Long University)'>Hanoi - Đại học Thăng Long (Thang Long University)</option>
<option value='Hanoi - Đại học Văn hóa Hà Nội (Hanoi University Of Culture)'>Hanoi - Đại học Văn hóa Hà Nội (Hanoi University Of Culture)</option>
<option value='Hanoi - Học viện Âm nhạc Quốc gia Việt Nam (Vietnam National Academy of Music)'>Hanoi - Học viện Âm nhạc Quốc gia Việt Nam (Vietnam National Academy of Music)</option>
<option value='Hanoi - Đại học Sư phạm Thể dục thể thao Hà nội'>Hanoi - Đại học Sư phạm Thể dục thể thao Hà nội</option>
<option value='Hanoi - Đại học Hòa Bình (Hoa Binh University)'>Hanoi - Đại học Hòa Bình (Hoa Binh University)</option>
<option value='Hanoi - Viện Đại học Mở Hà Nội (Hanoi Open University)'>Hanoi - Viện Đại học Mở Hà Nội (Hanoi Open University)</option>
<option value='Hanoi - Học viện Chính sách và Phát triển (Academy of Policy and Development)'>Hanoi - Học viện Chính sách và Phát triển (Academy of Policy and Development)</option>
<option value='Hanoi - Học viện Quản lý Giáo dục (National Institute of Education Management)'>Hanoi - Học viện Quản lý Giáo dục (National Institute of Education Management)</option>
<option value='Hanoi - Đại học Mỏ Địa chất Hà Nội (Hanoi University of Mining and Geology)'>Hanoi - Đại học Mỏ Địa chất Hà Nội (Hanoi University of Mining and Geology)</option>
<option value='Hanoi - Học viện Khoa học Quân sự (Military Science Academy)'>Hanoi - Học viện Khoa học Quân sự (Military Science Academy)</option>
<option value='Hanoi - Đại học Xây dựng (National University of Civil Engineering)'>Hanoi - Đại học Xây dựng (National University of Civil Engineering)</option>
<option value='Hanoi - Học viện Kỹ thuật Mật mã HN (Academy of Crytography Techniques)'>Hanoi - Học viện Kỹ thuật Mật mã HN (Academy of Crytography Techniques)</option>
<option value='Hanoi - Đại học Công nghiệp Hà Nội (Hanoi University of Industry)'>Hanoi - Đại học Công nghiệp Hà Nội (Hanoi University of Industry)</option>
<option value='Hanoi - Đại học Sân khấu Điện ảnh'>Hanoi - Đại học Sân khấu Điện ảnh</option>
<option value='Hanoi - Đại học Đông Đô (Dong Do University of Science and Technology)'>Hanoi - Đại học Đông Đô (Dong Do University of Science and Technology)</option>
<option value='Hanoi - Đại học Quốc tế Bắc Hà'>Hanoi - Đại học Quốc tế Bắc Hà</option>
<option value='Hanoi - Đại học Thành Đô'>Hanoi - Đại học Thành Đô</option>
<option value='Hanoi - Đại học Hàng Hải (Vietnam Maritime University)'>Hanoi - Đại học Hàng Hải (Vietnam Maritime University)</option>
<option value='Hanoi - Cao đẳng Y dược Thanh Hóa (Thanh Hoa Medical college)'>Hanoi - Cao đẳng Y dược Thanh Hóa (Thanh Hoa Medical college)</option>
<option value='Hanoi - Cao đẳng Cộng đồng Hà Nội (Hanoi Community College)'>Hanoi - Cao đẳng Cộng đồng Hà Nội (Hanoi Community College)</option>
<option value='Hanoi - Đại học Y Dược Hải Phòng (Hai Phong Medical University)'>Hanoi - Đại học Y Dược Hải Phòng (Hai Phong Medical University)</option>
<option value='Hanoi - Đại học Khoa học Thái Nguyên (Thai Nguyen University of Sciences (TNUS))'>Hanoi - Đại học Khoa học Thái Nguyên (Thai Nguyen University of Sciences (TNUS))</option>
<option value='Hanoi - Đại học Phương Đông (Phuong Dong University)'>Hanoi - Đại học Phương Đông (Phuong Dong University)</option>
<option value='Hanoi - Cao Đẳng Sư Phạm Hà Nội (Hanoi College of Education)'>Hanoi - Cao Đẳng Sư Phạm Hà Nội (Hanoi College of Education)</option>
<option value='Hanoi - Học viện Phụ nữ Việt Nam (Vietnam Women's Academy)'>Hanoi - Học viện Phụ nữ Việt Nam (Vietnam Womens Academy)</option>
<option value='Hanoi - VinUniversity'>Hanoi - VinUniversity</option>
<option value='Hanoi - Gap year after highschool in North region (exclude Hanoi)'>Hanoi - Gap year after highschool in North region (exclude Hanoi)</option>
<option value='Hanoi - Đại học Kinh tế Quốc dân (National Economics University)'>Hanoi - Đại học Kinh tế Quốc dân (National Economics University)</option>
<option value='Da Nang - Đại học Kinh tế Đà Nẵng (Da Nang University of Economics)'>Da Nang - Đại học Kinh tế Đà Nẵng (Da Nang University of Economics)</option>
<option value='Da Nang - Đại học Ngoại ngữ Đà Nẵng (Da Nang College of Foreign Languages)'>Da Nang - Đại học Ngoại ngữ Đà Nẵng (Da Nang College of Foreign Languages)</option>
<option value='Da Nang - Đại học Bách khoa Đà Nẵng (Da Nang University of Technology)'>Da Nang - Đại học Bách khoa Đà Nẵng (Da Nang University of Technology)</option>
<option value='Da Nang - Viện Nghiên Cứu & Đào Tạo Việt - Anh Đà Nẵng'>Da Nang - Viện Nghiên Cứu & Đào Tạo Việt - Anh Đà Nẵng</option>
<option value='Da Nang - Đại học Duy Tân (Duy Tan University)'>Da Nang - Đại học Duy Tân (Duy Tan University)</option>
<option value='Da Nang - Đại học Ngoại Ngữ - ĐH Huế (Hue University of Foreign Languages)'>Da Nang - Đại học Ngoại Ngữ - ĐH Huế (Hue University of Foreign Languages)</option>
<option value='Da Nang - Đại học Sư phạm Đà Nẵng (Da Nang College of Education)'>Da Nang - Đại học Sư phạm Đà Nẵng (Da Nang College of Education)</option>
<option value='Da Nang - Đại học Đà Nẵng Phân hiệu tại Kontum (Da Nang University Branch at Kontum)'>Da Nang - Đại học Đà Nẵng Phân hiệu tại Kontum (Da Nang University Branch at Kontum)</option>
<option value='Da Nang - Đại học Kỹ Thuật Y Dược Đà Nẵng (Danang University of Medical Technique)'>Da Nang - Đại học Kỹ Thuật Y Dược Đà Nẵng (Danang University of Medical Technique)</option>
<option value='Da Nang - Đại học FPT Đà Nẵng (Danang FPT University)'>Da Nang - Đại học FPT Đà Nẵng (Danang FPT University)</option>
<option value='Da Nang - Đại học Đông Á (Danang Dong A University)'>Da Nang - Đại học Đông Á (Danang Dong A University)</option>
<option value='Da Nang - Đại học Kiến trúc Đà Nẵng (Danang Architecture University)'>Da Nang - Đại học Kiến trúc Đà Nẵng (Danang Architecture University)</option>
<option value='Da Nang - Đại học Kỹ Thuật Y Dược (Danang University of Medical Technique)'>Da Nang - Đại học Kỹ Thuật Y Dược (Danang University of Medical Technique)</option>
<option value='Da Nang - Cao đẳng Công Nghệ - ĐH Đà Nẵng (Danang College of Industry)'>Da Nang - Cao đẳng Công Nghệ - ĐH Đà Nẵng (Danang College of Industry)</option>
<option value='Da Nang - Cao đẳng Công Nghệ Thông Tin - ĐH Đà Nẵng (Danang College of Information & Technology)'>Da Nang - Cao đẳng Công Nghệ Thông Tin - ĐH Đà Nẵng (Danang College of Information & Technology)</option>
<option value='Da Nang - Cao đẳng Công Nghệ Thông Tin Hữu Nghị Việt Hàn (Danang College of Information & Technology Vietnam-Korean)'>Da Nang - Cao đẳng Công Nghệ Thông Tin Hữu Nghị Việt Hàn (Danang College of Information & Technology Vietnam-Korean)</option>
<option value='Da Nang - Cao đẳng Công Nghệ Và Kinh Doanh Việt Tiến (Danang College of Industry & Business Viet Tien)'>Da Nang - Cao đẳng Công Nghệ Và Kinh Doanh Việt Tiến (Danang College of Industry & Business Viet Tien)</option>
<option value='Da Nang - Cao đẳng Dân Lập Kinh Tế Kỹ Thuật Đông Du Đà Nẵng (Danang College of Economic & Technology Dong Du)'>Da Nang - Cao đẳng Dân Lập Kinh Tế Kỹ Thuật Đông Du Đà Nẵng (Danang College of Economic & Technology Dong Du)</option>
<option value='Da Nang - Cao đẳng Giao Thông Vận Tải II (Danang College of Transport)'>Da Nang - Cao đẳng Giao Thông Vận Tải II (Danang College of Transport)</option>
<option value='Da Nang - Cao đẳng Kinh Tế - Kế Hoạch Đà Nẵng (Danang College of Economic)'>Da Nang - Cao đẳng Kinh Tế - Kế Hoạch Đà Nẵng (Danang College of Economic)</option>
<option value='Da Nang - Cao đẳng Lạc Việt (Danang Lac Viet College)'>Da Nang - Cao đẳng Lạc Việt (Danang Lac Viet College)</option>
<option value='Da Nang - Cao đẳng Lương Thực Thực Phẩm (Danang College of Food)'>Da Nang - Cao đẳng Lương Thực Thực Phẩm (Danang College of Food)</option>
<option value='Da Nang - Cao đẳng Phương Đông - Đà Nẵng (Danang Phuong Dong College)'>Da Nang - Cao đẳng Phương Đông - Đà Nẵng (Danang Phuong Dong College)</option>
<option value='Da Nang - Cao đẳng Thương Mại Đà Nẵng (Danang College of Commerce)'>Da Nang - Cao đẳng Thương Mại Đà Nẵng (Danang College of Commerce)</option>
<option value='Da Nang - Cao đẳng Tư Thục Đức Trí - Đà Nẵng (Danang Duc Tri College)'>Da Nang - Cao đẳng Tư Thục Đức Trí - Đà Nẵng (Danang Duc Tri College)</option>
<option value='Da Nang - Cao đẳng Công Nghiệp Huế (Hue College of Industry)'>Da Nang - Cao đẳng Công Nghiệp Huế (Hue College of Industry)</option>
<option value='Da Nang - Cao đẳng Sư Phạm Thừa Thiên Huế (Hue College of Education)'>Da Nang - Cao đẳng Sư Phạm Thừa Thiên Huế (Hue College of Education)</option>
<option value='Da Nang - Cao đẳng Xây Dựng Công Trình Đô Thị - Cơ Sở Huế (Hue College of Urban Construction Engineering)'>Da Nang - Cao đẳng Xây Dựng Công Trình Đô Thị - Cơ Sở Huế (Hue College of Urban Construction Engineering)</option>
<option value='Da Nang - Cao đẳng Y Tế Huế (Hue College of Medicine)'>Da Nang - Cao đẳng Y Tế Huế (Hue College of Medicine)</option>
<option value='Da Nang - Đại học Khoa Học - ĐH Huế (Hue University of Science)'>Da Nang - Đại học Khoa Học - ĐH Huế (Hue University of Science)</option>
<option value='Da Nang - Đại học Kinh Tế - ĐH Huế (Hue University of Economic)'>Da Nang - Đại học Kinh Tế - ĐH Huế (Hue University of Economic)</option>
<option value='Da Nang - Đại học Nghệ Thuật - ĐH Huế (Hue University of Arts)'>Da Nang - Đại học Nghệ Thuật - ĐH Huế (Hue University of Arts)</option>
<option value='Da Nang - Đại học Nông Lâm - ĐH Huế (Hue University of Agriculture and Forestry)'>Da Nang - Đại học Nông Lâm - ĐH Huế (Hue University of Agriculture and Forestry)</option>
<option value='Da Nang - Đại học Phú Xuân - Huế (Hue Phu Xuan University)'>Da Nang - Đại học Phú Xuân - Huế (Hue Phu Xuan University)</option>
<option value='Da Nang - Đại học Sư Phạm - ĐH Huế (Hue University of Education)'>Da Nang - Đại học Sư Phạm - ĐH Huế (Hue University of Education)</option>
<option value='Da Nang - Đại học Y Dược - ĐH Huế (Hue University of Medical)'>Da Nang - Đại học Y Dược - ĐH Huế (Hue University of Medical)</option>
<option value='Da Nang - Học viện Âm Nhạc Huế (Hue Academy of Music)'>Da Nang - Học viện Âm Nhạc Huế (Hue Academy of Music)</option>
<option value='Da Nang - Đại học Huế - Khoa Du Lịch (Hue University - Faculty of Tourism)'>Da Nang - Đại học Huế - Khoa Du Lịch (Hue University - Faculty of Tourism)</option>
<option value='Da Nang - Đại học Huế - Khoa Giáo Dục Thể Chất (Hue University - Faculty of Physical Education)'>Da Nang - Đại học Huế - Khoa Giáo Dục Thể Chất (Hue University - Faculty of Physical Education)</option>
<option value='Da Nang - Đại học Huế - Khoa Luật (Hue University - Faculty of Law)'>Da Nang - Đại học Huế - Khoa Luật (Hue University - Faculty of Law)</option>
<option value='Da Nang - Viện Nghiên Cứu Việt - Anh'>Da Nang - Viện Nghiên Cứu Việt - Anh</option><option value='HCMC - Đại học Kinh tế TP. HCM (University of Economics)'>HCMC - Đại học Kinh tế TP. HCM (University of Economics)</option>
<option value='HCMC - Đại học Khoa học Xã hội và Nhân văn (University of Social Sciences and Humanities)'>HCMC - Đại học Khoa học Xã hội và Nhân văn (University of Social Sciences and Humanities)</option>
<option value='HCMC - Đại học Quốc tế (International University)'>HCMC - Đại học Quốc tế (International University)</option>
<option value='HCMC - Đại học Hoa Sen (Hoa Sen University)'>HCMC - Đại học Hoa Sen (Hoa Sen University)</option>
<option value='HCMC - Đại học Y Dược (Ho Chi Minh University of Medicine and Pharmacy)'>HCMC - Đại học Y Dược (Ho Chi Minh University of Medicine and Pharmacy)</option>
<option value='HCMC - Đại học Công nghệ (HUTECH University HCM)'>HCMC - Đại học Công nghệ (HUTECH University HCM)</option>
<option value='HCMC - Đại học Kiến trúc (Ho Chi Minh City University of Architecture)'>HCMC - Đại học Kiến trúc (Ho Chi Minh City University of Architecture)</option>
<option value='HCMC - Đại học Y Pham Ngoc Thach (Pham Ngoc Thach University of Medicine)'>HCMC - Đại học Y Pham Ngoc Thach (Pham Ngoc Thach University of Medicine)</option>
<option value='HCMC - Đại học Thủy lợi (Water Resources University)'>HCMC - Đại học Thủy lợi (Water Resources University)</option>
<option value='HCMC - Đại học Lạc Hồng (Lac Hong University)'>HCMC - Đại học Lạc Hồng (Lac Hong University)</option>
<option value='HCMC - Đại học Sài Gòn (Saigon University)'>HCMC - Đại học Sài Gòn (Saigon University)</option>
<option value='HCMC - Cao đẳng kinh tế đối ngoại (College of Foreign Economic Relations)'>HCMC - Cao đẳng kinh tế đối ngoại (College of Foreign Economic Relations)</option>
<option value='HCMC - Đại học Pháp (French University - VietNam national university (HCM))'>HCMC - Đại học Pháp (French University - VietNam national university (HCM))</option>
<option value='HCMC - Đại học Hồng Đức (Hong Duc Medical School)'>HCMC - Đại học Hồng Đức (Hong Duc Medical School)</option>
<option value='HCMC - Đại học Troy (Troy University (HCM))'>HCMC - Đại học Troy (Troy University (HCM))</option>
<option value='HCMC - Đại học Tân Tạo (Tan Tao University)'>HCMC - Đại học Tân Tạo (Tan Tao University)</option>
<option value='HCMC - Học viện hàng không (Vietnam Aviation Academy)'>HCMC - Học viện hàng không (Vietnam Aviation Academy)</option>
<option value='HCMC - Nhạc viện (Conservatory of Ho Chi Minh City)'>HCMC - Nhạc viện (Conservatory of Ho Chi Minh City)</option>
<option value='HCMC - Đại học Mỹ Thuật (University of arts)'>HCMC - Đại học Mỹ Thuật (University of arts)</option>
<option value='HCMC - Trường trung cấp du lịch & khách sạn Saigontourist - Saigontourist Hospitality College'>HCMC - Trường trung cấp du lịch & khách sạn Saigontourist - Saigontourist Hospitality College</option>
<option value='HCMC - Khoa Y Đại học Quốc gia'>HCMC - Khoa Y Đại học Quốc gia</option>
<option value='HCMC - Đại học Tài chính - Kế Toán'>HCMC - Đại học Tài chính - Kế Toán</option>
<option value='HCMC - Đại Học Tư Thục Công Nghệ Thông Tin Gia Định'>HCMC - Đại Học Tư Thục Công Nghệ Thông Tin Gia Định</option>
<option value='HCMC - Cao đẳng Kinh tế - Kỹ thuật Vinatex TP.HCM'>HCMC - Cao đẳng Kinh tế - Kỹ thuật Vinatex TP.HCM</option>
<option value='HCMC - Cao đẳng Kinh tế TP.HCM'>HCMC - Cao đẳng Kinh tế TP.HCM</option>
<option value='HCMC - Cao đẳng Kỹ thuật Cao Thắng'>HCMC - Cao đẳng Kỹ thuật Cao Thắng</option>
<option value='HCMC - Cao đẳng Tài chính Hải quan'>HCMC - Cao đẳng Tài chính Hải quan</option>
<option value='HCMC - Cao đẳng Bách Việt'>HCMC - Cao đẳng Bách Việt</option>
<option value='HCMC - Cao đẳng Đại Việt Sài Gòn'>HCMC - Cao đẳng Đại Việt Sài Gòn</option>
<option value='HCMC - Cao đẳng Văn hóa Nghệ thuật và Du lịch Sài Gòn'>HCMC - Cao đẳng Văn hóa Nghệ thuật và Du lịch Sài Gòn</option>
<option value='HCMC - Học viện doanh nhân LP Việt Nam'>HCMC - Học viện doanh nhân LP Việt Nam</option><option value='HCMC - Đại học Ngoại thương HCM (Foreign Trade University - HCMC)'>HCMC - Đại học Ngoại thương HCM (Foreign Trade University - HCMC)</option>
<option value='HCMC - Đại học Ngân hàng (Banking University)'>HCMC - Đại học Ngân hàng (Banking University)</option>
<option value='HCMC - Đại học Ngoại ngữ và Công nghệ thông tin (HUFLIT) (University of Foreign Languages & Information Technology (HUFLIT))'>HCMC - Đại học Ngoại ngữ và Công nghệ thông tin (HUFLIT) (University of Foreign Languages & Information Technology (HUFLIT))</option>
<option value='HCMC - Đại học Tài Chính Marketing (University of Finance and Marketing)'>HCMC - Đại học Tài Chính Marketing (University of Finance and Marketing)</option>
<option value='HCMC - Đại học Sư phạm (University of Pedagogy)'>HCMC - Đại học Sư phạm (University of Pedagogy)</option>
<option value='HCMC - Đại học FPT HCM (FPT University)'>HCMC - Đại học FPT HCM (FPT University)</option>
<option value='HCMC - Đại học Công nghiệp (Industry University - HCMC)'>HCMC - Đại học Công nghiệp (Industry University - HCMC)</option>
<option value='HCMC - Đại học Hồng Bàng (Hong Bang University)'>HCMC - Đại học Hồng Bàng (Hong Bang University)</option>
<option value='HCMC - Đại học Công nghiệp Thực phẩm (HCMC University of Food Industry)'>HCMC - Đại học Công nghiệp Thực phẩm (HCMC University of Food Industry)</option>
<option value='HCMC - Đại học Tài nguyên và Môi trường (HCMC University of Natural Resources and Environment)'>HCMC - Đại học Tài nguyên và Môi trường (HCMC University of Natural Resources and Environment)</option>
<option value='HCMC - Đại học Giao thông vận tải HCM (University of Transport and Communication - Campus II)'>HCMC - Đại học Giao thông vận tải HCM (University of Transport and Communication - Campus II)</option>
<option value='HCMC - Học viện công nghệ bưu chính viễn thông HCMC (Posts and Telecommunications Institute of Technology)'>HCMC - Học viện công nghệ bưu chính viễn thông HCMC (Posts and Telecommunications Institute of Technology)</option>
<option value='HCMC - ERC International'>HCMC - ERC International</option>
<option value='HCMC - THPT Quốc tế Việt Úc (Saigon International College)'>HCMC - THPT Quốc tế Việt Úc (Saigon International College)</option>
<option value='HCMC - Đại học Vinh (Vinh University)'>HCMC - Đại học Vinh (Vinh University)</option>
<option value='HCMC - Học viện kĩ thuật mật mã HCM (Academy of Crytography Techniques)'>HCMC - Học viện kĩ thuật mật mã HCM (Academy of Crytography Techniques)</option>
<option value='HCMC - Đại học Hùng Vương (Hung Vuong university)'>HCMC - Đại học Hùng Vương (Hung Vuong university)</option>
<option value='HCMC - Trường Đại học kinh doanh quốc tế - University of Business International Studies (UBIS)'>HCMC - Trường Đại học kinh doanh quốc tế - University of Business International Studies (UBIS)</option>
<option value='HCMC - Trường đại học Dầu khí Việt Nam (PetroVietnam University - PVU)'>HCMC - Trường đại học Dầu khí Việt Nam (PetroVietnam University - PVU)</option>
<option value='HCMC - Broward College'>HCMC - Broward College</option>
<option value='HCMC - Đại học Văn Hiến (Văn Hiến University)'>HCMC - Đại học Văn Hiến (Văn Hiến University)</option>
<option value='HCMC - Học viện Cảnh sát Nhân dân'>HCMC - Học viện Cảnh sát Nhân dân</option>
<option value='HCMC - Đại học Lao động - Xã hội HCM'>HCMC - Đại học Lao động - Xã hội HCM</option>
<option value='HCMC - ĐH Sư phạm Thể dục Thể thao'>HCMC - ĐH Sư phạm Thể dục Thể thao</option>
<option value='HCMC - Cao đẳng Giao thông Vận tải'>HCMC - Cao đẳng Giao thông Vận tải</option>
<option value='HCMC - Cao đẳng Công thương'>HCMC - Cao đẳng Công thương</option>
<option value='HCMC - Cao đẳng Sư phạm Trung ương TP.HCM'>HCMC - Cao đẳng Sư phạm Trung ương TP.HCM</option>
<option value='HCMC - Cao đẳng Văn hóa Nghệ thuật TP.HCM'>HCMC - Cao đẳng Văn hóa Nghệ thuật TP.HCM</option>
<option value='HCMC - Cao đẳng Kỹ thuật Công nghệ Vạn Xuân'>HCMC - Cao đẳng Kỹ thuật Công nghệ Vạn Xuân</option>
<option value='HCMC - Cao đẳng Kinh tế - Công nghệ TP.HCM'>HCMC - Cao đẳng Kinh tế - Công nghệ TP.HCM</option>
<option value='HCMC - Cao đẳng Kinh tế Kỹ thuật Miền Nam'>HCMC - Cao đẳng Kinh tế Kỹ thuật Miền Nam</option>
<option value='HCMC - Cao đẳng Y tế Pasteur'>HCMC - Cao đẳng Y tế Pasteur</option>
<option value='HCMC - Cao đẳng Viễn Đông'>HCMC - Cao đẳng Viễn Đông</option>
<option value='HCMC - Arena Multimedia'>HCMC - Arena Multimedia</option><option value='HCMC - Đại học Kinh tế - Luật (University of Economics And Law)'>HCMC - Đại học Kinh tế - Luật (University of Economics And Law)</option>
<option value='HCMC - Đại học Luật (University of Law)'>HCMC - Đại học Luật (University of Law)</option>
<option value='HCMC - Đại học Sư phạm Kỹ thuật (University of Technology and Education HCM)'>HCMC - Đại học Sư phạm Kỹ thuật (University of Technology and Education HCM)</option>
<option value='HCMC - Đại học Khoa học Tự nhiên (University of Science)'>HCMC - Đại học Khoa học Tự nhiên (University of Science)</option>
<option value='HCMC - Đại học Mở (Open University)'>HCMC - Đại học Mở (Open University)</option>
<option value='HCMC - Đại học Công nghệ Thông tin (HCMC University of Information Technology)'>HCMC - Đại học Công nghệ Thông tin (HCMC University of Information Technology)</option>
<option value='HCMC - Đại học Đồng Nai (Dong Nai University)'>HCMC - Đại học Đồng Nai (Dong Nai University)</option>
<option value='HCMC - Đại học Nông Lâm (HCMC University of Agriculture and Forestry)'>HCMC - Đại học Nông Lâm (HCMC University of Agriculture and Forestry)</option>
<option value='HCMC - Đại học Thủ Dầu Một (Thu Dau Mot University)'>HCMC - Đại học Thủ Dầu Một (Thu Dau Mot University)</option>
<option value='HCMC - Đại học Quốc tế Miền Đông (Eastern International University)'>HCMC - Đại học Quốc tế Miền Đông (Eastern International University)</option>
<option value='HCMC - Đại học Việt Đức'>HCMC - Đại học Việt Đức</option>
<option value='HCMC - Đại học Công nghệ Đồng Nai'>HCMC - Đại học Công nghệ Đồng Nai</option>
<option value='HCMC - Đại học Kinh tế Kỹ thuật Bình Dương'>HCMC - Đại học Kinh tế Kỹ thuật Bình Dương</option>
<option value='HCMC - Đại học Bình Dương'>HCMC - Đại học Bình Dương</option>
<option value='HCMC - Đại học Lạc Hồng Đồng Nai'>HCMC - Đại học Lạc Hồng Đồng Nai</option>
<option value='HCMC - Đại học Công nghệ Miền Đông'>HCMC - Đại học Công nghệ Miền Đông</option>
<option value='HCMC - Đại học Lâm Nghiệp'>HCMC - Đại học Lâm Nghiệp</option>
<option value='HCMC - Đại Học Sunderland (The University of Sunderland)'>HCMC - Đại Học Sunderland (The University of Sunderland)</option>
<option value='HCMC - Cao đẳng Kinh Tế TPHCM (College of Economics)'>HCMC - Cao đẳng Kinh Tế TPHCM (College of Economics)</option><option value='HCMC - Đại học Văn Lang (Van Lang University)'>HCMC - Đại học Văn Lang (Van Lang University)</option>
<option value='HCMC - Đại học RMIT Hồ Chí Minh (RMIT Ho Chi Minh University)'>HCMC - Đại học RMIT Hồ Chí Minh (RMIT Ho Chi Minh University)</option>
<option value='HCMC - Đại học Tôn Đức Thắng (Ton Duc Thang University)'>HCMC - Đại học Tôn Đức Thắng (Ton Duc Thang University)</option>
<option value='HCMC - Đại học Bách Khoa HCM (University of Technology)'>HCMC - Đại học Bách Khoa HCM (University of Technology)</option>
<option value='HCMC - Đại học Kinh tế Tài chính (University of Economics and Finance)'>HCMC - Đại học Kinh tế Tài chính (University of Economics and Finance)</option>
<option value='HCMC - Viện đào tạo quốc tế đại học Nguyễn Tất Thành (Nguyen Tat Thanh Institute of International Education)'>HCMC - Viện đào tạo quốc tế đại học Nguyễn Tất Thành (Nguyen Tat Thanh Institute of International Education)</option>
<option value='HCMC - Đại học công nghệ Sài Gòn (Saigontech)'>HCMC - Đại học công nghệ Sài Gòn (Saigontech)</option>
<option value='HCMC - Đại học Văn hóa (Ho Chi Minh City University of Culture)'>HCMC - Đại học Văn hóa (Ho Chi Minh City University of Culture)</option>
<option value='HCMC - Đại học Cảnh Sát Nhân Dân (Peoples Police University)'>HCMC - Đại học Cảnh Sát Nhân Dân (People's Police University)</option>
<option value='HCMC - Cao đẳng nghề Việt Mỹ (Vietnamese American Training College)'>HCMC - Cao đẳng nghề Việt Mỹ (Vietnamese American Training College)</option>
<option value='HCMC - Học viện hành chính quốc gia (Ho Chi Minh National Academy of Politics and Public Administration)'>HCMC - Học viện hành chính quốc gia (Ho Chi Minh National Academy of Politics and Public Administration)</option>
<option value='HCMC - Đại học An Ninh nhân dân'>HCMC - Đại học An Ninh nhân dân</option>
<option value='HCMC - ĐH Sân khấu Điện ảnh'>HCMC - ĐH Sân khấu Điện ảnh</option>
<option value='HCMC - Đại học Trần Đại Nghĩa (Tran Dai Nghia University)'>HCMC - Đại học Trần Đại Nghĩa (Tran Dai Nghia University)</option>
<option value='HCMC - Cao đẳng BC Công nghệ và Quản trị doanh nghiệp'>HCMC - Cao đẳng BC Công nghệ và Quản trị doanh nghiệp</option>
<option value='HCMC - Cao đẳng Điện lực TP.HCM'>HCMC - Cao đẳng Điện lực TP.HCM</option>
<option value='HCMC - Cao đẳng Kinh tế Kỹ thuật TP. Hồ Chí Minh'>HCMC - Cao đẳng Kinh tế Kỹ thuật TP. Hồ Chí Minh</option>
<option value='HCMC - Cao đẳng Phát thanh Truyền hình 2'>HCMC - Cao đẳng Phát thanh Truyền hình 2</option>
<option value='HCMC - Cao đẳng Xây dựng số 2'>HCMC - Cao đẳng Xây dựng số 2</option><option value='Can Tho - Đại Học Cần Thơ'>Can Tho - Đại Học Cần Thơ</option>
<option value='Can Tho - Đại học Y Dược Cần Thơ'>Can Tho - Đại học Y Dược Cần Thơ</option>
<option value='Can Tho - Đại học Y Dược Cần Thơ'>Can Tho - Đại học Y Dược Cần Thơ</option>
<option value='Can Tho - Đại Học Nam Cần Thơ'>Can Tho - Đại Học Nam Cần Thơ</option>
<option value='Can Tho - Đại học Võ Trường Toản'>Can Tho - Đại học Võ Trường Toản</option>
<option value='Can Tho - Đại học Kỹ thuật công nghệ Cần Thơ'>Can Tho - Đại học Kỹ thuật công nghệ Cần Thơ</option>
<option value='Can Tho - Đại học Tây Đô'>Can Tho - Đại học Tây Đô</option>
<option value='Can Tho - Đại học Greenwich Cần Thơ'>Can Tho - Đại học Greenwich Cần Thơ</option>
<option value='Can Tho - Cao đẳng Cần Thơ'>Can Tho - Cao đẳng Cần Thơ</option>
<option value='Can Tho - Cao đẳng Cơ điện tử vầ Nông nghiệp Nam Bộ'>Can Tho - Cao đẳng Cơ điện tử vầ Nông nghiệp Nam Bộ</option>
<option value='Can Tho - Cao đẳng Kinh tế Kỹ thuật Cần Thơ'>Can Tho - Cao đẳng Kinh tế Kỹ thuật Cần Thơ</option>
<option value='Can Tho - Cao đẳng Nghề Cần Thơ'>Can Tho - Cao đẳng Nghề Cần Thơ</option>
<option value='Can Tho - Cao đẳng Nghề CNTT Ispace'>Can Tho - Cao đẳng Nghề CNTT Ispace</option>
<option value='Can Tho - Cao đẳng Nghề Việt Mỹ'>Can Tho - Cao đẳng Nghề Việt Mỹ</option>
<option value='Can Tho - Cao đẳng Y tế Cần Thơ'>Can Tho - Cao đẳng Y tế Cần Thơ</option>
<option value='Can Tho - Cao đẳng nghề Du lịch Cần Thơ'>Can Tho - Cao đẳng nghề Du lịch Cần Thơ</option>

